- name: "[CleanUp]: Removing kafka cluster along with monitoring"
  hosts: localhost
  vars:
     ansible_python_interpreter: /usr/bin/python3
     KAFKA_NAMESPACE: "{{ lookup('env','KAFKA_NAMESPACE') }}"
     MONITORING_NAMESPACE: "{{ lookup('env','MONITORING_NAMESPACE') }}"
  tasks:
     - name: "[CleanUp]: Removing  the deployments of prometheus"
       community.kubernetes.k8s:
          state: absent
          name: prometheus-operator
          kind: Deployment
          namespace: '{{ MONITORING_NAMESPACE }}'

     - name: "[CleanUp]: Removing Grafana deployment"
       community.kubernetes.k8s:
          state: absent
          name: grafana
          kind: Deployment
          namespace: '{{ MONITORING_NAMESPACE }}'

     - name: "[CleanUp]: Removing prometheus-k8s Statefulsets"
       community.kubernetes.k8s:
          api_version: apps/v1
          state: absent
          name: prometheus-k8s
          kind: StatefulSet
          namespace: '{{ MONITORING_NAMESPACE }}'
 
     - name: "[CleanUp]: Removing '{{ MONITORING_NAMESPACE }}' namespace"
       community.kubernetes.k8s:
          state: absent
          name: '{{ MONITORING_NAMESPACE }}'
          kind: namespace
                     
     - name: "[CleanUp]: Removing '{{ KAFKA_NAMESPACE }}'"
       community.kubernetes.k8s:
          state: absent
          name: '{{ KAFKA_NAMESPACE }}'
          kind: namespace
