---
- name: "[Info]:  Creating  litmus  namespace"
  community.kubernetes.k8s:
    name: litmus
    api_version: v1
    kind: Namespace
    state: present

- name: "[Install]: Installing chaos-exporter-service-monitor"
  command: kubectl apply -f service-monitors/chaos-exporter-service-monitor.yaml
 
- name: "[Info]: Assigning the namespace to kafka-exporter-service-monitor"
  replace:
    path: service-monitors/kafka-exporter-service-monitor.yaml
    regexp: 'NAMESPACE'
    replace: '{{ KAFKA_NAMESPACE }}'
    backup: yes

- name: "[Install]: Installing  kafka exporter service monitor"
  command: "kubectl apply -f service-monitors/kafka-exporter-service-monitor.yaml "
  
- name: "[Install]: Installing chaos-exporter"
  command: "kubectl apply -f chaos-exporter -n litmus"

- name: "[Install]: Installing kafka-exporter"
  command: "helm upgrade --install  -f kafka-exporter/values.yaml kafka-exporter --namespace={{ KAFKA_NAMESPACE }} ./kafka-exporter"
     
- name: "[Info]: Labeling servicemonitor"
  shell:
     cmd: "kubectl label servicemonitor.monitoring.coreos.com kafka-monitor -n {{  KAFKA_NAMESPACE }}  k8s-app=kafka-exporter --overwrite"
  register: monitor_log
- debug:
     var: monitor_log

- name: "[Install]: Installing prometheus for exporter"
  command: "kubectl apply -f prometheus/prometheus.yaml -n {{ MONITORING_NAMESPACE }}"

- name: "[Info]: Wait till prometheus-k8s created "
  community.kubernetes.k8s_info:
     api_version: apps/v1
     kind: StatefulSet
     wait: yes
     name: prometheus-k8s
     namespace: '{{ MONITORING_NAMESPACE }}'
     wait_sleep: 10
     wait_timeout: 180 
  
- name: "[CleanUp]: Removing litmus directory"
  file:
     path: litmus
     state: absent
     force: true

- name: "[Info]:  Pods in Kafka namespace"
  command: "kubectl get pods -n $KAFKA_NAMESPACE"
  register: kafka_pods
- debug:
     var: kafka_pods.stdout_lines

- name: "[Info]: Pods in monitoring  namespace"
  command: "kubectl get pods -n  $MONITORING_NAMESPACE"
  register: monitoring_pods
- debug:
     var: monitoring_pods.stdout_lines

- name: "[Info]: Pods in litmus namespace"
  command: kubectl get pods -n litmus
  register: litmus_pods
- debug:
     var: litmus_pods.stdout_lines

- name: "[Info]: Services in Monitoring"
  command: "kubectl get svc -n $MONITORING_NAMESPACE"
  register: monitoring_svc
- debug:
     var: monitoring_svc.stdout_lines
