apiVersion: v1
kind: ServiceAccount
metadata:
    name: litmus-kafka-sa
    namespace: default
    labels:
      name: litmus-kafka-sa
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: litmus-kafka-sa
  labels:
    name: litmus-kafka-sa
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: litmus-kafka-sa
  labels:
    name: litmus-kafka-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: litmus-kafka-sa
subjects:
- kind: ServiceAccount
  name: litmus-kafka-sa
  namespace: default
