#!/bin/bash
set -e

IMAGEID=$( docker images -q uditgaurav/argocli )

if [ ! -z "${DNAME}" ] && [ ! -z "${DPASS}" ];
then
  docker login -u "${DNAME}" -p "${DPASS}";
  #Push to docker hub repository with latest tag
  docker buildx build -f Dockerfile --progress plane --push --no-cache --platform linux/arm64,linux/amd64 --tag uditgaurav/argocli:v2.9.3 .
else
  echo "No docker credentials provided. Skip uploading uditgaurav/argocli:v2.9.3 to docker hub";
fi;
